import { GameItem } from "@/interfaces/game.interface";

export const SHOPS: GameItem[] = [
  {
    id: "lemonade_stand",
    name: "Lemonade Stand",
    description: "A small stand selling refreshing lemonade",
    baseCost: 10,
    baseIncome: 1,
    count: 0,
    level: 1,
    upgradeMultiplier: 1.5,
    upgradeCostMultiplier: 2,
  },
  {
    id: "newspaper_delivery",
    name: "Newspaper Delivery",
    description: "Deliver newspapers around the neighborhood",
    baseCost: 50,
    baseIncome: 5,
    count: 0,
    level: 1,
    upgradeMultiplier: 1.5,
    upgradeCostMultiplier: 2,
  },
  {
    id: "car_wash",
    name: "Car Wash",
    description: "Clean cars for quick cash",
    baseCost: 250,
    baseIncome: 15,
    count: 0,
    level: 1,
    upgradeMultiplier: 1.5,
    upgradeCostMultiplier: 2,
  },
  {
    id: "pizza_shop",
    name: "Pizza Shop",
    description: "Sell delicious pizzas",
    baseCost: 1000,
    baseIncome: 50,
    count: 0,
    level: 1,
    upgradeMultiplier: 1.5,
    upgradeCostMultiplier: 2,
  },
  {
    id: "tech_startup",
    name: "Tech Startup",
    description: "Launch the next big app",
    baseCost: 5000,
    baseIncome: 250,
    count: 0,
    level: 1,
    upgradeMultiplier: 1.5,
    upgradeCostMultiplier: 2,
  },
];
